remote_theme: kosatyi/sjt

navigation: false
projects: true

baseurl: /node-gettext-generator

brand: node-gettext-generator
title: Node Gettext Generator
description: Generate translation from your project source files to *.po files and compile to *.mo

author:
  name: Stepan Kosatyi
  url: https://kosatyi.com/