plugins:
  - jekyll-seo-tag

port: 4001

styles:

remote_theme: kosatyi/sjt

exclude:
  - vendor

javascript:

baseurl: /node-gettext-generator

navigation: false

projects: true

brand: node-gettext-generator
title: Node Gettext Generator
description: Generate translation from your project source files to *.po files and compile to *.mo
analytics: UA-37629144-1

author:
  name: Stepan Kosatyi
  url: http://www.kosatyi.com/

toolbar:
